# Generated by Django 5.2.7 on 2025-10-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='razor_payment_intent',
            new_name='razor_payment_id',
        ),
    ]
