# Generated by Django 5.2.7 on 2025-10-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
