# Generated by Django 5.2.7 on 2025-10-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderdetail_receipt_alter_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
