# Generated by Django 5.2.7 on 2025-10-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='razor_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
