# Generated by Django 5.2.7 on 2025-12-08 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
