# Generated by Django 5.2.7 on 2025-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_orderdetail_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
