# Generated by Django 5.2.7 on 2025-12-09 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_orderdetail_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
