# Generated by Django 5.2.7 on 2025-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_orderdetail_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='razor_order_id',
            field=models.CharField(default='TEMP', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='razor_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
