# Generated by Django 5.2.7 on 2025-12-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_orderdetail_razor_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='receipt',
        ),
    ]
